# Generated by Django 3.1.6 on 2022-11-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_participant_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_price',
            new_name='max_price',
        ),
    ]
